namespace AdventOfCode.Tests.Y2025.Day07;

using AdventOfCode.Y2025.Day07;

public class Y2025Day07Test : SolverTest<Y2025Day07>
{
    private static readonly string Input = """
                                           .......S.......
                                           ...............
                                           .......^.......
                                           ...............
                                           ......^.^......
                                           ...............
                                           .....^.^.^.....
                                           ...............
                                           ....^.^...^....
                                           ...............
                                           ...^.^...^.^...
                                           ...............
                                           ..^...^.....^..
                                           ...............
                                           .^.^.^.^.^...^.
                                           ...............
                                           """;

    protected override IEnumerable<TestCase> PartOnes() => [new(Input, 21)];

    protected override IEnumerable<TestCase> PartTwos() => [new(Input, 40)];
}
