namespace AdventOfCode.Tests.Y2024.Day08;

using AdventOfCode.Y2024.Day08;

public class Y2024Day08Test : SolverTest<Y2024Day08>
{
    private static readonly string Input = """
                                           ............
                                           ........0...
                                           .....0......
                                           .......0....
                                           ....0.......
                                           ......A.....
                                           ............
                                           ............
                                           ........A...
                                           .........A..
                                           ............
                                           ............
                                           """;

    protected override IEnumerable<TestCase> PartOnes() => [new(Input, 14)];

    protected override IEnumerable<TestCase> PartTwos() => [new(Input, 34)];
}
